import { Happy_Monkey } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar";
import Head from "next/head";
const HappyMonkey = Happy_Monkey({ 
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
 });

export const metadata = {
  title: "Kidnest",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="icon" href="/favicon.ico" sizes="any" />

      </Head>
      <body className={HappyMonkey.className}>
       
        {children}
      </body>
    </html>
  );
}
